crm_accounting/urls.py
from django.urls import path, include
from . import views

app_name = 'crm_accounting'

urlpatterns = [

    # accounts
    # path('account/detail/<int:pk>/', views.main_page, name='account_detail'),


    # counter
    # path('account/counter/detail/<int:pk>/', views.main_page,
    #      name='counter_data'),

    # transaction приходная ведомость
    path('account/', views.AccountListView.as_view(), name='account_list'),
    path('account/get-ajax-list/', views.AccountListViewAjax.as_view(),
         name='get_account_ajax_list'),
    path('account/create/', views.AccountCreateView.as_view(),
         name='account_create'),
    path('account/detail/<int:pk>/', views.PersonalAccountDetailView.as_view(),
         name='detail_account'),
    path('account/update/<int:pk>/', views.PersonalAccountUpdateView.as_view(),
         name='account_update'),
    path('account/delete/', views.DeletePersonalAccount.as_view(),
         name='delete_account'),
    path('account/get-excel/', views.DownloadExcelAccounts.as_view(),
         name='get_accounts_excel'),



    path('get-flats/', views.get_flats, name='get_flats'),
    path('get-users/', views.get_users, name='get_users'),


    path('transactions/', views.TransactionListView.as_view(),
         name='transaction_list'),
    path('account/transaction/', views.main_page,
         name='transaction_account_detail'),
    path('transactions/create/', views.TransactionCreateView.as_view(),
         name='transaction_create'),
    path('transactions/update/<int:pk>/',
         views.TransactionUpdateView.as_view(),
         name='transaction_update'),
    path('transactions/detail/<int:pk>/',
         views.TransactionDetailView.as_view(),
         name='transaction_detail'),
    path('transactions/delete/', views.DeleteTransaction.as_view(),
         name='delete_transaction'),
    path('transactions/export/', views.download_file,
         name='export_transaction'),
    path('transactions/download-excell/',
         views.DownloadExcelTransaction.as_view(),
         name='download_excel_transaction'),
    path('transactions/get-personal-accounts-ajax/',
         views.get_personal_accounts_ajax,
         name='get_personal_accounts_ajax'),
    path('transactions/get-ajax-transaction-list/',
         views.TransactionListViewAjax.as_view(),
         name='get_transaction_ajax_list'),



    # invoices
    path('account/invoice/detail/<int:pk>/', views.main_page,
         name='invoices_for_flat'),
    path('invoices/', views.InvoiceListView.as_view(), name='invoice_list'),
    path('invoices/get-ajax-list/', views.InvoiceListViewAjax.as_view(),
         name='get_invoices_ajax_list'),
    path('invoices/create/', views.InvoiceCreateView.as_view(),
         name='invoice_create'),
    path('invoices/detail/<int:pk>/', views.InvoiceDetailView.as_view(),
         name='invoice_detail'),
    path('invoices/update/<int:pk>/', views.InvoiceUpdateView.as_view(),
         name='invoice_update'),
    path('invoices/delete/', views.InvoiceDeleteView.as_view(),
         name='delete_invoice'),
    path('invoices/get-section-flat-ajax/', views.SectionAjaxView.as_view(),
         name='get_section_and_flat'),
    path('invoices/get-flats-ajax/', views.FlatAjaxList.as_view(),
         name='invoice_get_flats'),
    path('invoices/get-info-by-flat/', views.FlatAjaxInfo.as_view(),
         name='get_info_by_flat'),
    path('invoices/get-tariff-info/', views.tariff_ajax_info,
         name="get_tariff_info"),
    path('invoices/print/<int:pk>/', views.TemplatePrintView.as_view(),
         name='print_invoice'),
    path('invoices/template/', views.TemplatesUpdateView.as_view(),
         name='update_templates'),

    #
    path('transactionыаыфав/create/', views.TransactionCreateView.as_view(),
         name='transaction_account_create'),

]

home24/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('samartsev/', admin.site.urls),
    path('', include('content.urls')),
    path('admin/', include('houses.urls')),
    path('crm-accounting/', include('crm_accounting.urls')),
    path('system-settings/', include('crm_home.urls')),
    path('users/', include('users.urls')),
]

handler404 = 'users.views.handlers404'
handler403 = 'users.views.handler403'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include, register_converter
from . import views



app_name = 'users'
urlpatterns = [
    path('accounts/login/', views.LoginUser.as_view(), name='login'),
    path('accounts/register/', views.RegisterUserView.as_view(),
         name='register'),
    path('accounts/register-done/', views.RegisterDoneView.as_view(),
         name='register_done'),
    path('confirm/<str:sign>/', views.confirm_register,
         name='confirm_register'),
    path('accounts/admin-login/', views.LoginAdminUser.as_view(),
         name='admin-login'),
    path('accounts/logout/', views.LogoutUser.as_view(),
         name='logout'),

    path('', views.UsersListView.as_view(), name='users'),
    path('create/', views.UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', views.UserUpdateView.as_view(),
         name='user_update'),
    path('detail/<int:pk>/', views.UserDetailView.as_view(),
         name='user_detail'),
    path('delete/<int:pk>/', views.delete_user, name='user_delete'),

    path('ajax-user-list/', views.AjaxUsersListView.as_view(),
         name='ajax-users'),

    # owners
    path('owner/', views.OwnerListView.as_view(), name='owner_list'),
    path('owner/create/', views.OwnerCreateView.as_view(),
         name='owner_create'),
    path('owner/update/<int:pk>/', views.OwnerUpdateView.as_view(),
         name='owner_update'),
    path('owner/detail/<int:pk>/', views.OwnerDetailView.as_view(),
         name='owner_detail'),
    path('owner/delete/', views.OwnerListView.as_view(), name='owner_delete'),


    #CABINET

    path('cabinet/statistic/', views.CabinetStatisticView.as_view(),
         name='statistic_user_view'),
    path('cabinet/invoices/', views.CabinetInvoicesListView.as_view(),
         name='invoice_for_users'),
    path('cabinet/invoices/<int:pk>/', views.CabinetInvoicesDetail.as_view(),
         name='detail_invoice_for_users'),
    path('cabinet/invoices/ajax-request/',
         views.CabinetInvoicesAjaxList.as_view(),
         name='invoice_for_users_ajax'),

    #TARIFF
    path('cabinet/tariff/', views.CabinetTariffForFlatView.as_view(),
         name='tariff_for_users_flat'),
    #MESSAGES
    path('cabinet/messages/', views.MessageUserList.as_view(),
         name='messages_view'),
    path('cabinet/messages/ajax-list/', views.MessageUserAjaxList.as_view(),
         name='messages_user_ajax'),
    path('cabinet/messages/delete/', views.MessageUserAjaxDelete.as_view(),
         name='messages_user_delete'),
    path('cabinet/messages/<int:pk>/', views.MessageUserDetailView.as_view(),
         name='messages_user_detail'),

    #REQUESTS
    path('cabinet/master-request/',
         views.RequestUserListView.as_view(),
         name='request_user_view'),
    path('cabinet/master-request/get-ajax-list/',
         views.RequestUserAjaxListView.as_view(),
         name='request_user_ajax_list'),
    path('cabinet/master-request/create/',
         views.RequestUserCreateView.as_view(),
         name='request_user_create'),
    path('cabinet/master-request/delete/',
         views.RequestUserAjaxDelete.as_view(),
         name='request_user_delete'),

    #PROFILE
    path('cabinet/profile/',
         views.ProfileUserView.as_view(),
         name='user_profile'),
    path('cabinet/profile/update/',
         views.ProfileUserUpdate.as_view(),
         name='user_profile_update'),



    # request
    path('requests/', views.RequestListView.as_view(), name='requests_list'),
    path('requests-get-ajax/', views.RequestGetViewAjax.as_view(),
         name='requests_get_ajax_list'),
    path('delete-request-ajax/', views.RequestDeleteAjax.as_view(),
         name='requests_delete_ajax'),
    path('requests/create/', views.RequestsCreateView.as_view(),
         name='requests_create'),
    path('ajax-user-flats/', views.AjaxUserFlatsList.as_view(),
         name='ajax_user_flats'),
    path('requests/update/<int:pk>/', views.RequestUpdateView.as_view(),
         name='requests_update'),
    path('requests/detail/<int:pk>/', views.RequestDetailView.as_view(),
         name='requests_detail'),

    # MESSAGES
    path('messages/', views.MessageListView.as_view(),
         name='message_list'),
    path('messages/get-ajax-list/', views.MessageAjaxList.as_view(),
         name='message_get_ajax_list'),

    path('messages/get-ajax-house/', views.MessageAjaxHouseInfo.as_view(),
         name='message_ajax_info_for_house'),
    path('messages/delete/', views.MessageAjaxDelete.as_view(),
         name='messages_delete'),

    path('messages/get-ajax-section/', views.MessageAjaxSectionInfo.as_view(),
         name='message_ajax_info_for_section'),

    path('messages/create/', views.MessageCreateView.as_view(),
         name='message_create'),
    path('messages/detail/<int:pk>/', views.MessageDetailView.as_view(),
         name='message_detail'),
]

crm_accounting/models.py
import datetime

from django.db import models
from users.models import CustomUser
from crm_home.models import Tariff, Service, Unit, PaymentState
from home24 import settings


def get_next_transaction():
    ''' Getiing next number of transaction '''
    try:
        number_list = Transaction.objects.all().order_by('-number').\
            values('number')
        values_list = list()
        for item in number_list:
            values_list.append(item['number'])

        def check_instance(numbers, values, step=1):
            new_number = str(int(numbers[0]['number']) + step).zfill(11)
            if new_number in values:
                step += 1
                check_instance(numbers, values, step)
            else:
                return new_number
        return check_instance(number_list, values_list)
    except IndexError:
        new_number = str(1).zfill(11)
        return new_number


def get_next_account(count=None):
    """ Getiing next number of account """
    if not count:
        try:
            number = PersonalAccount.objects.order_by('-account_number')[0]
            return str(int(number.account_number) + 1).zfill(11)
        except IndexError:
            return str(1).zfill(11)
    else:
        try:
            numbers = PersonalAccount.objects.order_by('-account_number')[0]
            account_list = []
            for number in range(1, count):
                account_list.append(
                    str(int(numbers.account_number) + number).zfill(11))
        except IndexError:
            account_list = [str(1).zfill(11), str(2).zfill(11)]
        return account_list


class PersonalAccount(models.Model):
    account_number = models.CharField(default=get_next_account, unique=True,
                                      max_length=14)
    house = models.ForeignKey("houses.House", on_delete=models.CASCADE,
                              null=True, blank=True)
    section = models.ForeignKey('houses.Section', on_delete=models.SET_NULL,
                                null=True, blank=True)
    flat = models.ForeignKey('houses.Flat', on_delete=models.SET_NULL,
                             null=True, blank=True)
    status_choice = [('active', "Активен"), ('nonactive', "Неактивен")]
    status = models.CharField(choices=status_choice, null=True, blank=True,
                              max_length=20)
    balance = models.DecimalField(decimal_places=2, max_digits=10, default=0)

    class Meta:
        verbose_name_plural = "Персональные счета"
        verbose_name = "Персональный счет"

    def __str__(self):
        return str(self.account_number)




def get_next_invoice():
    ''' Getiing next number of transaction '''
    try:
        number_list = Invoice.objects.all().order_by('-number'). \
            values('number')
        values_list = list()
        for item in number_list:
            values_list.append(item['number'])
        def check_instance(numbers, values, step=1):
            new_number = str(int(numbers[0]['number']) + step).zfill(11)
            if new_number in values:
                step += 1
                check_instance(numbers, values, step)
            else:
                return new_number

        return check_instance(number_list, values_list)
    except IndexError:
        new_number = str(1).zfill(11)
        return new_number


status_invoice = [('', 'Выберите...'),
                  ('Оплачена', 'Оплачена'),
                  ('Частично оплачена', 'Частично оплачена'),
                  ('Неоплачена', 'Неоплачена')]


class Invoice(models.Model):
    number = models.CharField(unique=True, default=get_next_invoice,
                              max_length=15)
    date = models.DateField(default=datetime.datetime.now)
    house = models.ForeignKey('houses.House', on_delete=models.CASCADE)
    section = models.ForeignKey('houses.Section', on_delete=models.CASCADE,
                                null=True, blank=True)
    flat = models.ForeignKey('houses.Flat', on_delete=models.CASCADE)
    personal_account = models.CharField(max_length=50, null=True, blank=True)
    payment_state = models.BooleanField(verbose_name='Проведена',
                                        null=True, blank=True)
    status = models.CharField(max_length=120,
                              choices=status_invoice,
                              null=True,
                              default="Неоплачена",
                              blank=True)
    tariff = models.ForeignKey(Tariff, on_delete=models.PROTECT)
    period_start = models.DateField(default=datetime.datetime.now)
    period_end = models.DateField(default=datetime.datetime.now)
    amount = models.DecimalField(decimal_places=2, max_digits=10)

    class Meta:
        verbose_name_plural = 'Квитанции'
        verbose_name = 'Квитанция'

    def __str__(self):
        return self.number


class Transaction(models.Model):
    number = models.CharField(default=get_next_transaction, max_length=15)
    date = models.DateField(default=datetime.datetime.now)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE,
                              related_name='owner', null=True, blank=True)
    personal_account = models.ForeignKey(PersonalAccount,
                                         on_delete=models.PROTECT,
                                         null=True, blank=True)
    payment_state = models.ForeignKey(PaymentState, on_delete=models.PROTECT)
    amount = models.DecimalField(decimal_places=2, max_digits=10)
    completed = models.BooleanField(null=True, blank=True, default=True)
    manager = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.PROTECT,
                                null=True, blank=True)
    comment = models.TextField(max_length=1000, null=True, blank=True)

    def __str__(self):
        return self.number

    class Meta:
        verbose_name_plural = 'Транзакции'
        verbose_name = 'Транзакция'


class InvoiceService(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, null=True)
    service = models.ForeignKey(Service, on_delete=models.CASCADE, null=True)
    price = models.DecimalField(decimal_places=2, max_digits=10, null=True,
                                blank=True)
    amount = models.DecimalField(decimal_places=2, max_digits=10, null=True,
                                 blank=True)
    total = models.DecimalField(decimal_places=2, max_digits=10, null=True,
                                blank=True)

    def __str__(self):
        return f'{self.invoice} {self.service}'

    class Meta:
        verbose_name_plural = 'Квитанции с услугами'
        verbose_name = 'Квитанция с услугами'


class Template(models.Model):
    file = models.FileField(upload_to='templates_invoice/', null=True,
                            blank=True)
    name = models.CharField(max_length=20, default='New template')
    default = models.BooleanField(null=True, blank=True, default=False)

    def __str__(self):
        if self.default:
            return f'{self.name} (по-умолчанию)'
        else:
            return f'{self.name}'

templates/crm_accounting/template_print_view.html
{% extends 'houses/layout/base_houses.html' %}
{% load static %}
{% block title %}
    Печатная форма документа
{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'content/css/content_css.css' %}" type="text/css">
{% endblock %}
{% block css_after %}
    <link rel="stylesheet" href="{% static 'crm_accounting/css/invoice_create.css' %}">
{% endblock %}
{% block content %}
            <input type="hidden" id="link-id" value="invoice">

    <section class="content-header" style="position: relative; display: block!important; border-bottom: 1px solid #d2d6de">
        <h1 style="color: #444; font-size: 24px"> Печатная форма документа
        </h1>
        <ul class="breadcrumb" style="float:right;background: transparent!important; margin-top: 0!important;
        margin-bottom: 0!important; font-size: 12px!important; position: absolute!important;
        top: 15px!important; right: 15px!important; border-radius: 2px!important;">
            <li><a href="{% url 'houses:main' %}" style="color: #444; text-decoration: none"><i class="fa fa-home" style="margin-right: 5px"></i> Главная</a></li>
            <li class="active" style="padding: 0 0 0 10px; color: #777;"><a href="{% url 'crm_accounting:invoice_list' %}" style="color: #444; text-decoration: none">
                <span style="color: #ccc; margin-right: 5px" >></span> Квитанции
                </a>
            </li>
            <li class="active" style="padding: 0 0 0 10px; color: #777;"><a href="{% url 'crm_accounting:invoice_detail' object.id %}" style="color: #444; text-decoration: none">
                <span style="color: #ccc; margin-right: 5px" >></span> Квитанция № {{ object.number }}
                </a>
            </li>
            <li style="padding: 0 0 0 10px; color: #777;"><span style="color: #ccc; margin-right: 5px" >></span> Печатная форма документа </li>
        </ul>
    </section>

    <section class="content content-custom" style="font-size: 14px">
        <div class="box-header with-border" style="border-top: 3px solid #d2d6de">
                <h3 class="box-title">Список шаблонов</h3>
            <div class="box-tools">
                    <a style="height: 31px" href="{% url 'crm_accounting:update_templates' %}" class="btn btn-default btn-sm">
                    <span class="hidden-xs">Настройка шаблонов</span>
                    </a>
                </a>
            </div>
        </div>
        <div class="box" style="border-top: none">
        <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
            <div class="box-body">
            <div id="id_template">
                {% for radio in templates.template %}
                <div>
                <label for="{{ radio.id_for_label }}" style="font-weight: 400">
                    <span class="radio">{{ radio.tag }}</span>
                     {{ radio.choice_label }}
               </label>
                </div>
                {% endfor %}
            </div>
            <div class="row" style="justify-content: right">
                        <button style="width: min-content; margin-right: 10px" class="btn btn-success" name="action_download" type="submit">Скачать</button>
                        <button style="width: max-content" class="btn btn-default" name="action_send_email" type="submit">Отправить на e-mail</button>
                    </div>
            </div>
        </form>
        </div>
   </section>

  <script>
  </script>
{% endblock %}
{% block script %}


{% endblock %}

templates/crm_accounting/transaction_detail.html
{% extends 'houses/layout/base_houses.html' %}
{% load static %}
{% block title %}
    {{ type }}
{% endblock %}
{% block css %}

    <link rel="stylesheet" href="{% static 'content/css/content_css.css' %}" type="text/css">
{% endblock %}
{% block css_after %}
    <link rel="stylesheet" href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.10.3/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'crm_home/css/counter_create.css' %}">
        <input type="hidden" id="link-id" value="transaction">

{% endblock %}
{% block content %}
    <section class="content-header" style="position: relative; display: block!important; border-bottom: 1px solid #d2d6de">
        <h1 style="color: #444; font-size: 24px">     {{ type }}
        </h1>
        <ul class="breadcrumb" style="float:right;background: transparent!important; margin-top: 0!important;
        margin-bottom: 0!important; font-size: 12px!important; position: absolute!important;
        top: 15px!important; right: 15px!important; border-radius: 2px!important;">
            <li><a href="{% url 'houses:main' %}" style="color: #444; text-decoration: none"><i class="fa fa-home" style="margin-right: 5px"></i> Главная</a></li>
            <li class="active" style="padding: 0 0 0 10px; color: #777;"><a href="{% url 'crm_accounting:transaction_list' %}" style="color: #444; text-decoration: none">
                <span style="color: #ccc; margin-right: 5px" >></span> Платежи
                </a>
            </li>
            <li style="padding: 0 0 0 10px; color: #777;"><span style="color: #ccc; margin-right: 5px" >></span>{{ type }} №{{ object.number }}</li>
        </ul>
    </section>
    <form method="post" style="padding:15px">
        {% csrf_token %}
    <div class="row">
        <div class="col-xs-12 col-md-7 col-lg-6">
            <div class="page-header-spec" style="align-items: normal; justify-content: flex-start; margin-bottom: 0">
                <div class="form-group" style="margin-bottom: 0; width: 45%">
                    <div class="input-group">
                        <div class="input-group-addon">
                            №
                        </div>
                        <div class="input-group-addon" style="width:75%; text-align: left">
                            {{ object.number }}
                        </div>
                    </div>
                </div>
                <span class="label-mid" style="vertical-align: center; padding-top: 8px;margin: 0 auto 0 0; font-size: 14px">
                    от
                </span>
                <div class="form-group" style="width: 45%">
                    <div class="input-group" >
                        <div class="input-group-addon" style="width:75%; text-align: left">
                            {{ object.date|date:'d.m.Y' }}
                        </div>
                        <div class="input-group-addon">
                            <i class='fa fa-calendar' ></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- content -->
    <section class="content content-custom" >

        <div class="row">
            <div class="col-sm-12">
                <div class="box">
                    <div class="box-body">
                <div class="box-header" style="position: relative; height: 42px; padding: 0!important; margin-bottom: 10px!important;">
                    <h3 class="box-title">
                        {{ type }}
                    </h3>
                    <div class="box-tools">
                        <a href="{% url 'crm_accounting:transaction_create' %}?transaction_id={{ object.id }}" class="btn btn-default btn-sm">
                            <span class="hidden-xs">Копировать</span>
                        </a>
                        {% if user.is_superuser %}
                        <a href="{% url 'crm_accounting:delete_transaction'%}?transaction_id={{ object.id }}" class="btn btn-default btn-sm">
                            <span class="hidden-xs">Удалить</span>
                        </a>
                        {% else %}
                        <a href="#" onclick="alert('У Вас нет прав для удаления ведомости.')" disabled="" class="btn btn-default btn-sm">
                            <span class="hidden-xs">Удалить</span>
                        </a>
                        {% endif %}

                        <a href="{% url 'crm_accounting:transaction_update' object.id %}" style="padding: 4px 8px!important;" class="btn btn-tariff btn-sm">
                            <span class="hidden-xs">Редактировать ведомость</span>
                        </a>
                        <a href="{% url 'crm_accounting:export_transaction' %}?transaction_id={{ object.id }}" class="btn btn-default btn-sm">
                            <span class="hidden-xs">Выгрузить в Excel</span>
                        </a>
        </div>
                </div>
                                <div class="col-sm-12">
                        <table class="table table-bordered table-striped table-view" >
                    <tbody>
                        <tr>
                            <td class="user-label">Владелец квартиры</td>
                            <td style="width: 60%">
                                {% if object.owner %}
                                    <a class="link-list" href="{% url 'users:owner_detail' object.owner.id %}">
                                        {{ object.owner }}
                                    </a>
                                {% else %}
                                Не указано
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <td class="user-label">Лицевой счет</td>
                            <td>{% if object.personal_account %}
                                    <a class="link-list" href="{% url 'crm_accounting:detail_account' object.personal_account.id %}">
                                        {{ object.personal_account }}
                                    </a>
                                {% else %}
                                Не указано
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <td class="user-label">Статья</td>
                                <td>{{ object.payment_state }}</td>
                        </tr>
                        <tr>
                            <td class="user-label">Квитанция</td>
                            <td style="color: red">НЕ ПОНЯТНО ПОКА</td>
                        </tr>
                        <tr>
                            <td class="user-label">УСЛУГА</td>
                            <td style="color: red">ТОЖЕ НЕ ПОНЯТНО ПОКА</td>
                        </td>
                        </tr>
                        <tr>
                            <td class="user-label">Менеджер</td>
                            <td style="width: 60%">
                                {% if object.manager %}
                                    <a class="link-list" href="{% url 'users:user_detail' object.manager.id %}">
                                        {{ object.manager }}
                                    </a>
                                {% else %}
                                Не указано
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <td class="user-label">Сумма</td>
                            <td style="width: 60%">
                                {% if type == 'Приходная ведомость'%}
                                    <span style="color: #00a65a">{{ object.amount }}</span>
                                    {% else %}
                                    <span style="color: red">{{ object.amount }}</span>
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <td class="user-label">Комментарий</td>
                                <td>
                                {% if object.comment %}
                                    {{ object.comment }}
                                    {% else %}
                                    Не выбран
                                {% endif %}
                                    </td>
                        </tr>

                    </tbody>
                </table>

                    </div>
                                </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    </form>
    <div>
    </div>
{% endblock %}
{% block script %}
    <script src="{% static 'crm_accounting/js/account_create.js' %}"></script>
{% endblock %}