crm_accounting/urls.py
from django.urls import path, include
from . import views

app_name = 'crm_accounting'

urlpatterns = [

    # accounts
    # path('account/detail/<int:pk>/', views.main_page, name='account_detail'),


    # counter
    # path('account/counter/detail/<int:pk>/', views.main_page,
    #      name='counter_data'),

    # transaction приходная ведомость
    path('account/', views.AccountListView.as_view(), name='account_list'),
    path('account/get-ajax-list/', views.AccountListViewAjax.as_view(),
         name='get_account_ajax_list'),
    path('account/create/', views.AccountCreateView.as_view(),
         name='account_create'),
    path('account/detail/<int:pk>/', views.PersonalAccountDetailView.as_view(),
         name='detail_account'),
    path('account/update/<int:pk>/', views.PersonalAccountUpdateView.as_view(),
         name='account_update'),
    path('account/delete/', views.DeletePersonalAccount.as_view(),
         name='delete_account'),
    path('account/get-excel/', views.DownloadExcelAccounts.as_view(),
         name='get_accounts_excel'),



    path('get-flats/', views.get_flats, name='get_flats'),
    path('get-users/', views.get_users, name='get_users'),


    path('transactions/', views.TransactionListView.as_view(),
         name='transaction_list'),
    path('account/transaction/', views.main_page,
         name='transaction_account_detail'),
    path('transactions/create/', views.TransactionCreateView.as_view(),
         name='transaction_create'),
    path('transactions/update/<int:pk>/',
         views.TransactionUpdateView.as_view(),
         name='transaction_update'),
    path('transactions/detail/<int:pk>/',
         views.TransactionDetailView.as_view(),
         name='transaction_detail'),
    path('transactions/delete/', views.DeleteTransaction.as_view(),
         name='delete_transaction'),
    path('transactions/export/', views.download_file,
         name='export_transaction'),
    path('transactions/download-excell/',
         views.DownloadExcelTransaction.as_view(),
         name='download_excel_transaction'),
    path('transactions/get-personal-accounts-ajax/',
         views.get_personal_accounts_ajax,
         name='get_personal_accounts_ajax'),
    path('transactions/get-ajax-transaction-list/',
         views.TransactionListViewAjax.as_view(),
         name='get_transaction_ajax_list'),



    # invoices
    path('account/invoice/detail/<int:pk>/', views.main_page,
         name='invoices_for_flat'),
    path('invoices/', views.InvoiceListView.as_view(), name='invoice_list'),
    path('invoices/get-ajax-list/', views.InvoiceListViewAjax.as_view(),
         name='get_invoices_ajax_list'),
    path('invoices/create/', views.InvoiceCreateView.as_view(),
         name='invoice_create'),
    path('invoices/detail/<int:pk>/', views.InvoiceDetailView.as_view(),
         name='invoice_detail'),
    path('invoices/update/<int:pk>/', views.InvoiceUpdateView.as_view(),
         name='invoice_update'),
    path('invoices/delete/', views.InvoiceDeleteView.as_view(),
         name='delete_invoice'),
    path('invoices/get-section-flat-ajax/', views.SectionAjaxView.as_view(),
         name='get_section_and_flat'),
    path('invoices/get-flats-ajax/', views.FlatAjaxList.as_view(),
         name='invoice_get_flats'),
    path('invoices/get-info-by-flat/', views.FlatAjaxInfo.as_view(),
         name='get_info_by_flat'),
    path('invoices/get-tariff-info/', views.tariff_ajax_info,
         name="get_tariff_info"),
    path('invoices/print/<int:pk>/', views.TemplatePrintView.as_view(),
         name='print_invoice'),
    path('invoices/template/', views.TemplatesUpdateView.as_view(),
         name='update_templates'),

    #
    path('transactionыаыфав/create/', views.TransactionCreateView.as_view(),
         name='transaction_account_create'),

]

crm_home/urls.py
from django.urls import path, include
from . import views

app_name = 'crm_home'
urlpatterns = [
    path('set-services/', views.ServiceSettings.as_view(),
         name='set_services'),

    # tariff
    path('tariff/', views.TariffListView.as_view(), name='tariffs'),
    path('tariff/create/', views.TariffCreateVIew.as_view(),
         name='tariff_create'),
    path('tariff/update/<int:pk>/', views.TariffUpdateView.as_view(),
         name='tariff_update'),
    path('tariff/delete/', views.delete_tariff,
         name='delete_tariff'),
    path('tariff/<int:pk>/', views.TariffDetailView.as_view(),
         name='tariff_detail'),
    path('get-unit-for-service/', views.get_unit_for_service,
         name='unit_for_service'),

    # roles
    path('roles/update/', views.RolesUpdateView.as_view(),
         name='roles'),

    # requisites
    path('requisites/', views.RequisitesUpdateView.as_view(),
         name='requisites'),

    #payment state
    path('payment-states/', views.PaymentStateListView.as_view(),
         name='payment_states'),
    path('payment-states/create/', views.PaymentStateCreateView.as_view(),
         name='payment_state_create'),
    path('payment-states/update/<int:pk>/',
         views.PaymentStateUpdateView.as_view(), name='payment_state_update'),
    path('payment-states/delete/', views.delete_payment_state,
         name='payment_state_delete'),


    #counter
    path('counter-data/', views.CounterDataListView.as_view(),
         name='counter_data_list'),
    path('counter-data/flat-counter-list/',
         views.FlatCounterDataListView.as_view(),
         name='flat_counter_list'),



    path('counter-data-ajax-list/', views.CounterDataListViewAjax.as_view(),
         name='counter_data_list_ajax'),
    path('counters-flat-ajax/', views.FlatCounterDataGetViewAjax.as_view(),
         name='counter_data-flat_get_ajax'),
    path('counter-data/delete', views.CounterDeleteAjax.as_view(),
         name='counter_delete_ajax'),
    path('counter-data/create/', views.CounterDataCreateView.as_view(),
         name='counter_data_create'),
    path('counter-data/detail/<int:pk>/',
         views.CounterDetailView.as_view(),
         name='counter_data_detail'),
    path('counter-data/update/<int:pk>/',
         views.CounterDataUpdateView.as_view(),
         name='counter_data_update'),


]

home24/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('samartsev/', admin.site.urls),
    path('', include('content.urls')),
    path('admin/', include('houses.urls')),
    path('crm-accounting/', include('crm_accounting.urls')),
    path('system-settings/', include('crm_home.urls')),
    path('users/', include('users.urls')),
]

handler404 = 'users.views.handlers404'
handler403 = 'users.views.handler403'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

houses/urls.py
from django.urls import path, include
from django.views.defaults import permission_denied, page_not_found

from . import views




app_name = 'houses'


urlpatterns = [
    path('main/', views.main_page, name='main'),

    #statistics
    path('', views.StatisticView.as_view(), name='statistics'),

    # houses
    path('houses/', views.HousesListView.as_view(), name='house_list'),
    path('houses/create/', views.HouseCreateView.as_view(), name='house_create'),
    path('houses/detail/<int:pk>/', views.HousesDetail.as_view(), name='house_detail'),
    path('houses/update/<int:pk>/', views.HouseUpdateView.as_view(), name='house_update'),
    path('houses/delete/', views.delete_house, name='delete_house'),
    path('houses/create/get-role/', views.get_role, name='get_role'),


    # flats
    path('flats/', views.FlatsListView.as_view(), name='flat_list'),
    path('flats/create/', views.FlatCreate.as_view(), name='flat_create'),
    path('flats/detail/<int:pk>/', views.FlatDetailView.as_view(), name='flat_detail'),
    path('flats/update/<int:pk>/', views.FlatUpdateView.as_view(), name='flat_update'),
    path('get-account-list/', views.get_account_list, name='get_account_list'),
    path('get-sections-and-floors/', views.get_sections_and_floors, name='get_section_and_floor'),
    path('flats/detail/<int:pk>/', views.HousesDetail.as_view(), name='flat_detail'),
    path('flats/delete/', views.delete_flat, name="delete_flat"),
    path('ajax-data-table/', views.FlatsListViewAjax.as_view(), name='get_ajax'),


    # path('create/', views.HousesListView.as_view(), name='house_create'),

    # path('about-us/', views.about, name='about'),
    # path('services/', views.services, name='services'),
    # path('contacts/', views.contacts, name='contacts'),

]

users/urls.py
from django.urls import path, include, register_converter
from . import views



app_name = 'users'
urlpatterns = [
    path('accounts/login/', views.LoginUser.as_view(), name='login'),
    path('accounts/register/', views.RegisterUserView.as_view(),
         name='register'),
    path('accounts/register-done/', views.RegisterDoneView.as_view(),
         name='register_done'),
    path('confirm/<str:sign>/', views.confirm_register,
         name='confirm_register'),
    path('accounts/admin-login/', views.LoginAdminUser.as_view(),
         name='admin-login'),
    path('accounts/logout/', views.LogoutUser.as_view(),
         name='logout'),

    path('', views.UsersListView.as_view(), name='users'),
    path('create/', views.UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', views.UserUpdateView.as_view(),
         name='user_update'),
    path('detail/<int:pk>/', views.UserDetailView.as_view(),
         name='user_detail'),
    path('delete/<int:pk>/', views.delete_user, name='user_delete'),

    path('ajax-user-list/', views.AjaxUsersListView.as_view(),
         name='ajax-users'),

    # owners
    path('owner/', views.OwnerListView.as_view(), name='owner_list'),
    path('owner/create/', views.OwnerCreateView.as_view(),
         name='owner_create'),
    path('owner/update/<int:pk>/', views.OwnerUpdateView.as_view(),
         name='owner_update'),
    path('owner/detail/<int:pk>/', views.OwnerDetailView.as_view(),
         name='owner_detail'),
    path('owner/delete/', views.OwnerListView.as_view(), name='owner_delete'),


    #CABINET

    path('cabinet/statistic/', views.CabinetStatisticView.as_view(),
         name='statistic_user_view'),
    path('cabinet/invoices/', views.CabinetInvoicesListView.as_view(),
         name='invoice_for_users'),
    path('cabinet/invoices/<int:pk>/', views.CabinetInvoicesDetail.as_view(),
         name='detail_invoice_for_users'),
    path('cabinet/invoices/ajax-request/',
         views.CabinetInvoicesAjaxList.as_view(),
         name='invoice_for_users_ajax'),

    #TARIFF
    path('cabinet/tariff/', views.CabinetTariffForFlatView.as_view(),
         name='tariff_for_users_flat'),
    #MESSAGES
    path('cabinet/messages/', views.MessageUserList.as_view(),
         name='messages_view'),
    path('cabinet/messages/ajax-list/', views.MessageUserAjaxList.as_view(),
         name='messages_user_ajax'),
    path('cabinet/messages/delete/', views.MessageUserAjaxDelete.as_view(),
         name='messages_user_delete'),
    path('cabinet/messages/<int:pk>/', views.MessageUserDetailView.as_view(),
         name='messages_user_detail'),

    #REQUESTS
    path('cabinet/master-request/',
         views.RequestUserListView.as_view(),
         name='request_user_view'),
    path('cabinet/master-request/get-ajax-list/',
         views.RequestUserAjaxListView.as_view(),
         name='request_user_ajax_list'),
    path('cabinet/master-request/create/',
         views.RequestUserCreateView.as_view(),
         name='request_user_create'),
    path('cabinet/master-request/delete/',
         views.RequestUserAjaxDelete.as_view(),
         name='request_user_delete'),

    #PROFILE
    path('cabinet/profile/',
         views.ProfileUserView.as_view(),
         name='user_profile'),
    path('cabinet/profile/update/',
         views.ProfileUserUpdate.as_view(),
         name='user_profile_update'),



    # request
    path('requests/', views.RequestListView.as_view(), name='requests_list'),
    path('requests-get-ajax/', views.RequestGetViewAjax.as_view(),
         name='requests_get_ajax_list'),
    path('delete-request-ajax/', views.RequestDeleteAjax.as_view(),
         name='requests_delete_ajax'),
    path('requests/create/', views.RequestsCreateView.as_view(),
         name='requests_create'),
    path('ajax-user-flats/', views.AjaxUserFlatsList.as_view(),
         name='ajax_user_flats'),
    path('requests/update/<int:pk>/', views.RequestUpdateView.as_view(),
         name='requests_update'),
    path('requests/detail/<int:pk>/', views.RequestDetailView.as_view(),
         name='requests_detail'),

    # MESSAGES
    path('messages/', views.MessageListView.as_view(),
         name='message_list'),
    path('messages/get-ajax-list/', views.MessageAjaxList.as_view(),
         name='message_get_ajax_list'),

    path('messages/get-ajax-house/', views.MessageAjaxHouseInfo.as_view(),
         name='message_ajax_info_for_house'),
    path('messages/delete/', views.MessageAjaxDelete.as_view(),
         name='messages_delete'),

    path('messages/get-ajax-section/', views.MessageAjaxSectionInfo.as_view(),
         name='message_ajax_info_for_section'),

    path('messages/create/', views.MessageCreateView.as_view(),
         name='message_create'),
    path('messages/detail/<int:pk>/', views.MessageDetailView.as_view(),
         name='message_detail'),
]

crm_home/models.py
import datetime
from django.db import models


class Unit(models.Model):
    title = models.CharField(max_length=30)

    def __str__(self):
        return self.title


class Service(models.Model):
    name = models.CharField(max_length=100)
    show = models.BooleanField(null=True, blank=True)
    unit = models.ForeignKey(Unit, on_delete=models.PROTECT, null=True,
                             blank=True)

    def __str__(self):
        return self.name


class Tariff(models.Model):
    name = models.CharField(max_length=100, error_messages=
                            {'required': 'Это поле обязательно к заполнению '
                                         'и не может быть пустым.'})
    describe = models.TextField(max_length=2000, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class TariffService(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE, null=True,
                                blank=True)
    tariff = models.ForeignKey(Tariff, on_delete=models.CASCADE, null=True,
                               blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=10, blank=True,
                                null=True, default=0)

    class Meta:
        verbose_name_plural = "Тарифы Услуги"
        verbose_name = "Тариф Услуга"

    def __str__(self):
        return f'{self.tariff} - {self.service}'
    # def clean_price(self):
    #     new_price = self.cleaned


def get_next_counter_number():
    """ Getting next number of counter """
    try:
        number = CounterData.objects.order_by('-id')[0].number
        x = str(int(number) + 1).zfill(10)
    except IndexError:
        x = str(1).zfill(10)
    return x


class CounterData(models.Model):
    number = models.CharField(default=get_next_counter_number, max_length=20,
                              unique=True)
    date = models.DateField(default=datetime.datetime.now)
    house = models.ForeignKey('houses.House', on_delete=models.CASCADE)
    section = models.ForeignKey('houses.Section', on_delete=models.CASCADE)
    flat = models.ForeignKey('houses.Flat', on_delete=models.CASCADE)
    StatusCounter = [("Новое", "Новое"), ("Учтено", "Учтено"),
                     ("Учтено и оплачено", "Учтено и оплачено"),
                     ("Нулевое", "Нулевое")]
    status = models.CharField(choices=StatusCounter, max_length=40)
    service = models.ForeignKey(Service, on_delete=models.PROTECT)
    data = models.DecimalField(decimal_places=2, max_digits=10)

    def __str__(self):
        return str(self.number)


class Requisites(models.Model):
    title = models.CharField(max_length=100)
    info = models.TextField(max_length=1000)

    def __str__(self):
        return f'{self.title} {self.info}'


class PaymentState(models.Model):
    title = models.CharField(max_length=100)
    type = models.CharField(choices=[("in", "Приход"),
                                     ("out", "Расход")],
                            max_length=30)

    def __str__(self):
        return self.title

templates/crm_home/counterdata_form.html
{% extends 'houses/layout/base_houses.html' %}
{% load static %}
{% block title %}
    Новое показание
{% endblock %}
{% block css %}

    <link rel="stylesheet" href="{% static 'content/css/content_css.css' %}" type="text/css">
{% endblock %}
{% block css_after %}
    <link rel="stylesheet" href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.10.3/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'crm_home/css/counter_create.css' %}">

{% endblock %}
{% block content %}
                                <input type="hidden" id="link-id" value="counter-link">

    <section class="content-header" style="position: relative; display: block!important; border-bottom: 1px solid #d2d6de">
        <h1 style="color: #444; font-size: 24px"> Новое показание
        </h1>
        <ul class="breadcrumb" style="float:right;background: transparent!important; margin-top: 0!important;
        margin-bottom: 0!important; font-size: 12px!important; position: absolute!important;
        top: 15px!important; right: 15px!important; border-radius: 2px!important;">
            <li><a href="{% url 'houses:main' %}" style="color: #444; text-decoration: none"><i class="fa fa-home" style="margin-right: 5px"></i> Главная</a></li>
            <li class="active" style="padding: 0 0 0 10px; color: #777;"><a href="{% url 'crm_home:counter_data_list' %}" style="color: #444; text-decoration: none">
                <span style="color: #ccc; margin-right: 5px" >></span> Счетчики
                </a>
            </li>
            <li style="padding: 0 0 0 10px; color: #777;"><span style="color: #ccc; margin-right: 5px" >></span> Новое показание</li>
        </ul>
    </section>
    <form method="post" style="padding:15px">
        {% csrf_token %}
    <div class="row">
        <div class="col-xs-12 col-md-7 col-lg-6">
            <div class="page-header-spec" style="align-items: normal; justify-content: flex-start">
                <div class="form-group" style="margin-bottom: 0px">
                    <div class="input-group">
                        <div class="input-group-addon">
                            №
                        </div>
                        {{ form.number }}
                    </div>
                    <div class="errorlist">
                        {% if form.errors.number %}
                            {% for field in form.errors.number %}
                                {{ field }}
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <span class="label-mid" style="vertical-align: center; padding-top: 10px;margin: 0 15px; font-size: 14px">
                    от
                </span>
                <div class="form-group">
                    <div class="input-group">
                        {{ form.date }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- content -->
    <section class="content content-custom" >
        <div class="row">
            <div class="col-sm-12">
                <div class="box">
                    <div class="box-body">
                            <div class="row">
                                <div class="col-xs-12 col-sm-6">

                                    <div class="form-group no-margin" style="margin-bottom: 0">
                                        {{ form.house.label_tag }}
                                        {{ form.house }}
                                    </div>
                                    <div class="form-group no-margin" style="margin-bottom: 0">
                                        {{ form.section.label_tag }}
                                        <select name="section" id="id_section"  class="form-select">
                                            <option value="">Выберите...</option>
                                            {% if form.initial.section %}
                                                <option value="{{ form.initial.section.id }}" selected>{{ form.initial.section }}</option>
                                            {% endif %}
                                        </select>
                                    </div>
                                    <div class="form-group no-margin" style="margin-bottom: 0">
                                        {{ form.flat.label_tag }}

                                        <select name="flat" id="id_flat" class="form-select">
                                            <option value="">Выберите...</option>
                                            {% if form.initial %}
                                                <option value="{{ form.initial.flat.id }}" selected>{{ form.initial.flat }}</option>
                                            {% endif %}
                                        </select>
                                        <div class="errorlist">
                                            {% if form.errors.flat %}
                                                {% for field in form.errors.flat %}
                                                    {{ field }}
                                                {% endfor %}
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="form-group no-margin" style="margin-bottom: 0">
                                        {{ form.service.label_tag }}
                                        {{ form.service }}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-6">
                                    <div class="form-group" style="margin-bottom: 0">
                                        {{ form.status.label_tag }}
                                        {{ form.status }}
                                    </div>
                                    <div class="form-group" style="margin-bottom: 0">
                                        {{ form.data.label_tag }}
                                        {{ form.data }}
                                    </div>
                                </div>
                                <div class="row" style="text-align: right">
                                    <div class="form-group">
                                        <a href="{% url 'crm_home:counter_data_list' %}" class="btn btn-default" style="height: 34px; font-size: 14px; background-color: #f4f4f4; color: #444!important;
                                        ">Отменить</a>
                                        <button type="submit" class="btn btn-success" name="save">Сохранить</button>
                                        <button type="submit" class="btn btn-success add-more" style="background-color: #008d4c" name="save_and_add">Сохранить и добавить новые показания</button>
                                    </div>
                                    </div>
                                </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    </form>

    <div>

    </div>
  <script>
  </script>
{% endblock %}
{% block script %}
    <script src="{% static 'crm_accounting/js/account_create.js' %}"></script>

    <script>
        function ajax_section (){
            const house = ($("#id_house").val())
            var empty_value = '<option value="">Выберите...</option>'

            if (house) {
                $.ajax({
                url: '{% url 'houses:get_section_and_floor' %}',
                type: 'get',
                data: {
                    'house': house,
                },
                success: (data) => {
                    var id_sections = $('#id_section');
                    id_sections.empty()
                    id_sections.append(empty_value)
                    var sections = '';

                    $(data.sectionist).each(function (index, value) {
                        sections += "<option value='"+value.id+"'>"+value.title+"</option>"
                    })
                    id_sections.append(sections)
                }
            })
            } else {
                $('#id_section').empty()
                $('#id_section').append(empty_value)
            }
        }
        function ajax_flat () {
            const section = ($('#id_section').val());
            var empty_value = '<option value="">Выберите...</option>'
            if (section) {
                $.ajax({
                    url: '{% url 'crm_accounting:get_flats' %}',
                    type: 'get',
                    data: {
                        'section': section,
                    },
                    success: (data) => {
                        var id_flats = $('#id_flat')
                        id_flats.empty()
                        id_flats.append(empty_value)
                        var flats = '';
                        $(data.flats).each(function(index, value) {
                            flats += "<option value='"+value.flat_id+"'>"+value.flat_number+"</option>"
                        })
                        id_flats.append(flats)
                    }
                })
            } else {
                $('#id_flat').empty().append(empty_value)

            }
        }
    </script>
    <script>
        $('#id_house').on('change', ajax_section)
        $('#id_section').on('change', ajax_flat)
        {#$('#id_flat').on('change', ajax_owner)#}
    </script>

    <script>
            window.onload =  function () {
                {#ajax_section()#}
                {#ajax_flat()#}
            }
    </script>

     <script>
    $(function () {
        $("#id_date").datepicker({
                showOn: "both",
              dateFormat: "yy-mm-dd"

            });
        $('.ui-datepicker-trigger').html("<i class='fa fa-calendar'></i>").addClass('btn btn-date').before($("#id_date"))

    })

    </script>


{% endblock %}

templates/crm_home/paymentstate_form.html
{% extends 'houses/layout/base_houses.html' %}
{% load static %}
{% block title %}
    Редактирование страницы
{% endblock %}
{% block css %}

    <link rel="stylesheet" href="{% static 'content/css/content_css.css' %}" type="text/css">
{% endblock %}
{% block css_after %}
    <link rel="stylesheet" href="{% static 'crm_home/css/payment.css' %}">
{% endblock %}
{% block content %}
                        <input type="hidden" id="link-id" value="settings-link">

    <section class="content-header" style="position: relative; display: block!important; border-bottom: 1px solid #d2d6de">
        <h1 style="color: #444; font-size: 24px"> Новая статья
        </h1>
        <ul class="breadcrumb" style="float:right;background: transparent!important; margin-top: 0!important;
        margin-bottom: 0!important; font-size: 12px!important; position: absolute!important;
        top: 15px!important; right: 10px!important; border-radius: 2px!important;">
            <li><a href="{% url 'houses:main' %}" style="color: #444; text-decoration: none"><i class="fa fa-home" style="margin-right: 5px"></i> Главная</a></li>
            <li style="padding: 0 0 0 10px; color: #777;"><a href="{% url 'crm_home:payment_states' %}" style="color: #444; text-decoration: none">> <span style="color: #ccc; margin-right: 5px" >></span> Статьи приходов/расходов</a></li>
            <li class="active" style="padding: 0 0 0 10px; color: #777;"> <span style="color: #ccc; margin-right: 5px" >></span> Новая статья</li>
        </ul>
    </section>
    <!-- content -->
    <section class="content content-custom" >

        <div class="row">
            <div class="col-sm-12">
                <form method="post">
                {% csrf_token %}
                <div class="box">
                    <div class="box-body">
                        <div class="row">
                            <div class="col-xs-12 col-lg-7">
                                <div class="form-group">
                                    {{ form.title.label_tag }}
                                    {{ form.title }}
                                    <div class="help-block" id='name-error' style="display: none">
                                        Необходимо заполнить «Название».
                                    </div>
                                </div>
                                <div class="form-group">
                                    {{ form.type.label_tag }}
                                    {{ form.type }}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="form-group" style="text-align: right">
                            <a href="{% url 'crm_home:payment_states' %}" class="btn btn-default" style="height: 34px; font-size: 14px; background-color: #f4f4f4; color: #444!important;
    border-color: #ddd!important;border-radius: 3px;">Отменить</a>
                            <button type="submit" class="btn btn-success" id="btn-save" >Сохранить</button>
                    </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </section>
{% endblock %}
{% block script %}
        <script src="{% static 'crm_home/js/payment.js' %}"></script>
{% endblock %}