crm_accounting/urls.py
from django.urls import path, include
from . import views

app_name = 'crm_accounting'

urlpatterns = [

    # accounts
    # path('account/detail/<int:pk>/', views.main_page, name='account_detail'),


    # counter
    # path('account/counter/detail/<int:pk>/', views.main_page,
    #      name='counter_data'),

    # transaction приходная ведомость
    path('account/', views.AccountListView.as_view(), name='account_list'),
    path('account/get-ajax-list/', views.AccountListViewAjax.as_view(),
         name='get_account_ajax_list'),
    path('account/create/', views.AccountCreateView.as_view(),
         name='account_create'),
    path('account/detail/<int:pk>/', views.PersonalAccountDetailView.as_view(),
         name='detail_account'),
    path('account/update/<int:pk>/', views.PersonalAccountUpdateView.as_view(),
         name='account_update'),
    path('account/delete/', views.DeletePersonalAccount.as_view(),
         name='delete_account'),
    path('account/get-excel/', views.DownloadExcelAccounts.as_view(),
         name='get_accounts_excel'),



    path('get-flats/', views.get_flats, name='get_flats'),
    path('get-users/', views.get_users, name='get_users'),


    path('transactions/', views.TransactionListView.as_view(),
         name='transaction_list'),
    path('account/transaction/', views.main_page,
         name='transaction_account_detail'),
    path('transactions/create/', views.TransactionCreateView.as_view(),
         name='transaction_create'),
    path('transactions/update/<int:pk>/',
         views.TransactionUpdateView.as_view(),
         name='transaction_update'),
    path('transactions/detail/<int:pk>/',
         views.TransactionDetailView.as_view(),
         name='transaction_detail'),
    path('transactions/delete/', views.DeleteTransaction.as_view(),
         name='delete_transaction'),
    path('transactions/export/', views.download_file,
         name='export_transaction'),
    path('transactions/download-excell/',
         views.DownloadExcelTransaction.as_view(),
         name='download_excel_transaction'),
    path('transactions/get-personal-accounts-ajax/',
         views.get_personal_accounts_ajax,
         name='get_personal_accounts_ajax'),
    path('transactions/get-ajax-transaction-list/',
         views.TransactionListViewAjax.as_view(),
         name='get_transaction_ajax_list'),



    # invoices
    path('account/invoice/detail/<int:pk>/', views.main_page,
         name='invoices_for_flat'),
    path('invoices/', views.InvoiceListView.as_view(), name='invoice_list'),
    path('invoices/get-ajax-list/', views.InvoiceListViewAjax.as_view(),
         name='get_invoices_ajax_list'),
    path('invoices/create/', views.InvoiceCreateView.as_view(),
         name='invoice_create'),
    path('invoices/detail/<int:pk>/', views.InvoiceDetailView.as_view(),
         name='invoice_detail'),
    path('invoices/update/<int:pk>/', views.InvoiceUpdateView.as_view(),
         name='invoice_update'),
    path('invoices/delete/', views.InvoiceDeleteView.as_view(),
         name='delete_invoice'),
    path('invoices/get-section-flat-ajax/', views.SectionAjaxView.as_view(),
         name='get_section_and_flat'),
    path('invoices/get-flats-ajax/', views.FlatAjaxList.as_view(),
         name='invoice_get_flats'),
    path('invoices/get-info-by-flat/', views.FlatAjaxInfo.as_view(),
         name='get_info_by_flat'),
    path('invoices/get-tariff-info/', views.tariff_ajax_info,
         name="get_tariff_info"),
    path('invoices/print/<int:pk>/', views.TemplatePrintView.as_view(),
         name='print_invoice'),
    path('invoices/template/', views.TemplatesUpdateView.as_view(),
         name='update_templates'),

    #
    path('transactionыаыфав/create/', views.TransactionCreateView.as_view(),
         name='transaction_account_create'),

]

crm_home/urls.py
from django.urls import path, include
from . import views

app_name = 'crm_home'
urlpatterns = [
    path('set-services/', views.ServiceSettings.as_view(),
         name='set_services'),

    # tariff
    path('tariff/', views.TariffListView.as_view(), name='tariffs'),
    path('tariff/create/', views.TariffCreateVIew.as_view(),
         name='tariff_create'),
    path('tariff/update/<int:pk>/', views.TariffUpdateView.as_view(),
         name='tariff_update'),
    path('tariff/delete/', views.delete_tariff,
         name='delete_tariff'),
    path('tariff/<int:pk>/', views.TariffDetailView.as_view(),
         name='tariff_detail'),
    path('get-unit-for-service/', views.get_unit_for_service,
         name='unit_for_service'),

    # roles
    path('roles/update/', views.RolesUpdateView.as_view(),
         name='roles'),

    # requisites
    path('requisites/', views.RequisitesUpdateView.as_view(),
         name='requisites'),

    #payment state
    path('payment-states/', views.PaymentStateListView.as_view(),
         name='payment_states'),
    path('payment-states/create/', views.PaymentStateCreateView.as_view(),
         name='payment_state_create'),
    path('payment-states/update/<int:pk>/',
         views.PaymentStateUpdateView.as_view(), name='payment_state_update'),
    path('payment-states/delete/', views.delete_payment_state,
         name='payment_state_delete'),


    #counter
    path('counter-data/', views.CounterDataListView.as_view(),
         name='counter_data_list'),
    path('counter-data/flat-counter-list/',
         views.FlatCounterDataListView.as_view(),
         name='flat_counter_list'),



    path('counter-data-ajax-list/', views.CounterDataListViewAjax.as_view(),
         name='counter_data_list_ajax'),
    path('counters-flat-ajax/', views.FlatCounterDataGetViewAjax.as_view(),
         name='counter_data-flat_get_ajax'),
    path('counter-data/delete', views.CounterDeleteAjax.as_view(),
         name='counter_delete_ajax'),
    path('counter-data/create/', views.CounterDataCreateView.as_view(),
         name='counter_data_create'),
    path('counter-data/detail/<int:pk>/',
         views.CounterDetailView.as_view(),
         name='counter_data_detail'),
    path('counter-data/update/<int:pk>/',
         views.CounterDataUpdateView.as_view(),
         name='counter_data_update'),


]

home24/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('samartsev/', admin.site.urls),
    path('', include('content.urls')),
    path('admin/', include('houses.urls')),
    path('crm-accounting/', include('crm_accounting.urls')),
    path('system-settings/', include('crm_home.urls')),
    path('users/', include('users.urls')),
]

handler404 = 'users.views.handlers404'
handler403 = 'users.views.handler403'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

houses/urls.py
from django.urls import path, include
from django.views.defaults import permission_denied, page_not_found

from . import views




app_name = 'houses'


urlpatterns = [
    path('main/', views.main_page, name='main'),

    #statistics
    path('', views.StatisticView.as_view(), name='statistics'),

    # houses
    path('houses/', views.HousesListView.as_view(), name='house_list'),
    path('houses/create/', views.HouseCreateView.as_view(), name='house_create'),
    path('houses/detail/<int:pk>/', views.HousesDetail.as_view(), name='house_detail'),
    path('houses/update/<int:pk>/', views.HouseUpdateView.as_view(), name='house_update'),
    path('houses/delete/', views.delete_house, name='delete_house'),
    path('houses/create/get-role/', views.get_role, name='get_role'),


    # flats
    path('flats/', views.FlatsListView.as_view(), name='flat_list'),
    path('flats/create/', views.FlatCreate.as_view(), name='flat_create'),
    path('flats/detail/<int:pk>/', views.FlatDetailView.as_view(), name='flat_detail'),
    path('flats/update/<int:pk>/', views.FlatUpdateView.as_view(), name='flat_update'),
    path('get-account-list/', views.get_account_list, name='get_account_list'),
    path('get-sections-and-floors/', views.get_sections_and_floors, name='get_section_and_floor'),
    path('flats/detail/<int:pk>/', views.HousesDetail.as_view(), name='flat_detail'),
    path('flats/delete/', views.delete_flat, name="delete_flat"),
    path('ajax-data-table/', views.FlatsListViewAjax.as_view(), name='get_ajax'),


    # path('create/', views.HousesListView.as_view(), name='house_create'),

    # path('about-us/', views.about, name='about'),
    # path('services/', views.services, name='services'),
    # path('contacts/', views.contacts, name='contacts'),

]

users/urls.py
from django.urls import path, include, register_converter
from . import views



app_name = 'users'
urlpatterns = [
    path('accounts/login/', views.LoginUser.as_view(), name='login'),
    path('accounts/register/', views.RegisterUserView.as_view(),
         name='register'),
    path('accounts/register-done/', views.RegisterDoneView.as_view(),
         name='register_done'),
    path('confirm/<str:sign>/', views.confirm_register,
         name='confirm_register'),
    path('accounts/admin-login/', views.LoginAdminUser.as_view(),
         name='admin-login'),
    path('accounts/logout/', views.LogoutUser.as_view(),
         name='logout'),

    path('', views.UsersListView.as_view(), name='users'),
    path('create/', views.UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', views.UserUpdateView.as_view(),
         name='user_update'),
    path('detail/<int:pk>/', views.UserDetailView.as_view(),
         name='user_detail'),
    path('delete/<int:pk>/', views.delete_user, name='user_delete'),

    path('ajax-user-list/', views.AjaxUsersListView.as_view(),
         name='ajax-users'),

    # owners
    path('owner/', views.OwnerListView.as_view(), name='owner_list'),
    path('owner/create/', views.OwnerCreateView.as_view(),
         name='owner_create'),
    path('owner/update/<int:pk>/', views.OwnerUpdateView.as_view(),
         name='owner_update'),
    path('owner/detail/<int:pk>/', views.OwnerDetailView.as_view(),
         name='owner_detail'),
    path('owner/delete/', views.OwnerListView.as_view(), name='owner_delete'),


    #CABINET

    path('cabinet/statistic/', views.CabinetStatisticView.as_view(),
         name='statistic_user_view'),
    path('cabinet/invoices/', views.CabinetInvoicesListView.as_view(),
         name='invoice_for_users'),
    path('cabinet/invoices/<int:pk>/', views.CabinetInvoicesDetail.as_view(),
         name='detail_invoice_for_users'),
    path('cabinet/invoices/ajax-request/',
         views.CabinetInvoicesAjaxList.as_view(),
         name='invoice_for_users_ajax'),

    #TARIFF
    path('cabinet/tariff/', views.CabinetTariffForFlatView.as_view(),
         name='tariff_for_users_flat'),
    #MESSAGES
    path('cabinet/messages/', views.MessageUserList.as_view(),
         name='messages_view'),
    path('cabinet/messages/ajax-list/', views.MessageUserAjaxList.as_view(),
         name='messages_user_ajax'),
    path('cabinet/messages/delete/', views.MessageUserAjaxDelete.as_view(),
         name='messages_user_delete'),
    path('cabinet/messages/<int:pk>/', views.MessageUserDetailView.as_view(),
         name='messages_user_detail'),

    #REQUESTS
    path('cabinet/master-request/',
         views.RequestUserListView.as_view(),
         name='request_user_view'),
    path('cabinet/master-request/get-ajax-list/',
         views.RequestUserAjaxListView.as_view(),
         name='request_user_ajax_list'),
    path('cabinet/master-request/create/',
         views.RequestUserCreateView.as_view(),
         name='request_user_create'),
    path('cabinet/master-request/delete/',
         views.RequestUserAjaxDelete.as_view(),
         name='request_user_delete'),

    #PROFILE
    path('cabinet/profile/',
         views.ProfileUserView.as_view(),
         name='user_profile'),
    path('cabinet/profile/update/',
         views.ProfileUserUpdate.as_view(),
         name='user_profile_update'),



    # request
    path('requests/', views.RequestListView.as_view(), name='requests_list'),
    path('requests-get-ajax/', views.RequestGetViewAjax.as_view(),
         name='requests_get_ajax_list'),
    path('delete-request-ajax/', views.RequestDeleteAjax.as_view(),
         name='requests_delete_ajax'),
    path('requests/create/', views.RequestsCreateView.as_view(),
         name='requests_create'),
    path('ajax-user-flats/', views.AjaxUserFlatsList.as_view(),
         name='ajax_user_flats'),
    path('requests/update/<int:pk>/', views.RequestUpdateView.as_view(),
         name='requests_update'),
    path('requests/detail/<int:pk>/', views.RequestDetailView.as_view(),
         name='requests_detail'),

    # MESSAGES
    path('messages/', views.MessageListView.as_view(),
         name='message_list'),
    path('messages/get-ajax-list/', views.MessageAjaxList.as_view(),
         name='message_get_ajax_list'),

    path('messages/get-ajax-house/', views.MessageAjaxHouseInfo.as_view(),
         name='message_ajax_info_for_house'),
    path('messages/delete/', views.MessageAjaxDelete.as_view(),
         name='messages_delete'),

    path('messages/get-ajax-section/', views.MessageAjaxSectionInfo.as_view(),
         name='message_ajax_info_for_section'),

    path('messages/create/', views.MessageCreateView.as_view(),
         name='message_create'),
    path('messages/detail/<int:pk>/', views.MessageDetailView.as_view(),
         name='message_detail'),
]

houses/models.py
from django.db import models

from crm_accounting.models import PersonalAccount
from crm_home.models import Tariff
from users.models import CustomUser


class House(models.Model):
    title = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    image_1 = models.ImageField(upload_to='house/', null=True, blank=True)
    image_2 = models.ImageField(upload_to='house/', null=True, blank=True)
    image_3 = models.ImageField(upload_to='house/', null=True, blank=True)
    image_4 = models.ImageField(upload_to='house/', null=True, blank=True)
    image_5 = models.ImageField(upload_to='house/', null=True, blank=True)
    users = models.ManyToManyField(CustomUser)

    class Meta:
        verbose_name_plural = 'Дома'
        verbose_name = 'Дом'

    def __str__(self):
        return self.title


class Section(models.Model):
    title = models.CharField(max_length=20, null=True, blank=True)
    house = models.ForeignKey(House, on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name_plural = 'Секции'
        verbose_name = 'Секция'

    def __str__(self):
        return f'{self.title}'


class Floor(models.Model):
    title = models.CharField(max_length=20, null=True, blank=True)
    house = models.ForeignKey(House, on_delete=models.CASCADE, null=True)


    class Meta:
        verbose_name_plural = 'Этажи'
        verbose_name = 'Этаж'

    def __str__(self):
        return self.title


class Flat(models.Model):
    number = models.IntegerField()
    area = models.FloatField()
    house = models.ForeignKey(House, on_delete=models.CASCADE)
    section = models.ForeignKey(Section, on_delete=models.CASCADE, null=True,
                                blank=True, error_messages=
                                {'required': 'Это поле обязательно.'})
    floor = models.ForeignKey(Floor, on_delete=models.CASCADE, null=True,
                              blank=True,)
    owner = models.ForeignKey(CustomUser, on_delete=models.PROTECT, null=True,
                              blank=True,)
    tariff = models.ForeignKey(Tariff, on_delete=models.PROTECT, null=True,
                               blank=True,)
    personal_account = models.OneToOneField(PersonalAccount,
                                            on_delete=models.SET_NULL,
                                            related_name='account_flat',
                                            null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Квартиры'
        verbose_name = 'Квартира'

    def __str__(self):
        return f'№{str(self.number)}'

templates/houses/flat/flat_detail.html
{% extends 'houses/layout/base_houses.html' %}
{% load static %}
{% block title %}
    Квартира №{{ object.number }}, {{ object.house }}
{% endblock %}
{% block css %}

    <link rel="stylesheet" href="{% static 'content/css/content_css.css' %}" type="text/css">
{% endblock %}
{% block css_after %}
    <link type="text/css" rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="{% static 'houses/css/houses.css' %}">
    <style>
        .disabled {
            pointer-events: all;
        }
    </style>
{% endblock %}
{% block content %}
            <input type="hidden" id="link-id" value="flat-link">

    <section class="content-header" style="position: relative; display: block!important; border-bottom: 1px solid #d2d6de">
        <h1 style="color: #444; font-size: 24px">Квартира №{{ object.number }}, {{ object.house }}
        </h1>
        <ul class="breadcrumb" style="float:right;background: transparent!important; margin-top: 0!important;
        margin-bottom: 0!important; font-size: 12px!important; position: absolute!important;
        top: 15px!important; right: 15px!important; border-radius: 2px!important;">
            <li><a href="{% url 'houses:main' %}" style="color: #444; text-decoration: none"><i class="fa fa-home" style="margin-right: 5px"></i> Главная</a></li>
            <li style="padding: 0 0 0 10px; color: #777;"><a href="{% url 'houses:flat_list' %}" style="color: #444; text-decoration: none"> <span style="color: #ccc; margin-right: 5px" >></span> Квартиры </a></li>
            <li class="active" style="padding: 0 0 0 10px; color: #777;"> <span style="color: #ccc; margin-right: 5px" >></span> Квартира №{{ object.number }}, {{ object.house }} </li>
        </ul>
    </section>
    <!-- content -->
    <section class="content content-custom" >

        <div class="row">
            <div class="col-sm-12">
                <div class="box">
                <div class="box-header" style="position: relative; height: 42px">
                    <h3 class="box-title">Просмотр квартиры</h3>
                    <div class="box-tools">
                        {% if object.personal_account %}
                            <a style="height: 31px" href="{% url 'crm_accounting:transaction_account_create' %}?flat_id={{ object.id }}" class="btn btn-default btn-sm">
                                {% else %}
                            <a style="height: 31px" class="btn btn-default btn-sm disabled" onclick="alert('У квартиры нет лицевого счета')">
                                {% endif %}
                    <span class="hidden-xs"><i class="fa fa-dollar"></i> Принять платеж</span>
                </a>
                    {% if object.personal_account %}
                <a style="height: 31px" href="{% url 'crm_accounting:invoice_list' %}?flat_id={{ object.id }}" class="btn btn-default btn-sm">
                   {% else %}
                            <a style="height: 31px" class="btn btn-default btn-sm disabled" onclick="alert('У квартиры нет лицевого счета')">
                   {% endif %}
                    <span class="hidden-xs"><i class="fa fa-files-o"></i> Оформить квитанцию</span>
                </a>
                        <a href="{% url 'houses:flat_update' object.id %}" class="btn btn-tariff btn-sm">
                <span class="hidden-xs">Редактировать квартиру</span>
            </a>
        </div>
                </div>
                    <div class="box-body row">
                    <div class="col-sm-12 col-lg-12">
                        <table class="table table-bordered table-striped table-view" >
                    <tbody>
                        <tr>
                            <td class="user-label">Лицевой счет</td>
                            {% if object.personal_account %}
                                <td>
                                    <a class="link-list" href="{% url 'crm_accounting:detail_account' object.personal_account.id %}">
                                        {{ object.personal_account }}
                                    </a>
                                </td>
                            {% else %}
                                <td>Не указано</td>
                            {% endif %}
                        </tr>
                        <tr>
                            <td class="user-label">Номер квартиры</td>
                            <td>{{ object.number }}</td>
                        </tr>
                        <tr>
                            <td class="user-label">Площадь</td>
                            {% if object.area %}
                                <td>{{ object.area }}м<sup>2</sup></td>
                                {% else %}
                                <td>Не указано</td>
                            {% endif %}
                        </tr>
                        <tr>
                            <td class="user-label">Дом</td>
                            <td><a class="link-list" href="{% url 'houses:house_detail' object.house.id %}">{{ object.house }}</a></td>
                        </tr>
                        <tr>
                            <td class="user-label">Секция</td>
                            <td>{{ object.section }}</td>
                        </tr>
                        <tr>
                            <td class="user-label">Этаж</td>
                            <td>
                                {{ object.floor }}
                            </td>
                        </tr>
                        <tr>
                            <td class="user-label">Владелец</td>
                            <td>
                                {% if object.owner %}
                                <a class="link-list" href="{% url 'users:owner_detail' object.owner.id %}">{{ object.owner }}</a>
                                {% else %}
                                    Владелец не указан
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <td class="user-label">Тариф</td>
                            <td>
                                {% if object.tariff %}
                                    {{ object.tariff }}
                                    {% else %}
                                    Не указано
                                {% endif %}
                            </td>
                        </tr>
                    </tbody>
                </table>
                    <div>
                    <p style="margin-bottom: 10px" ><a class="link-list" href="{% url 'crm_home:flat_counter_list' %}?flat_id={{ object.id }}">Посмотреть показания счетчиков</a></p>
                    <p style="margin-bottom: 10px" ><a class="link-list" href="{% url 'crm_accounting:transaction_account_detail' %}/?account={{ object.personal_account.id }}">Посмотреть приходы</a></p>
                    <p style="margin-bottom: 10px" ><a class="link-list" href="{% url 'crm_accounting:invoice_list' %}?flat_id={{ object.id }}">Посмотреть квитанции</a></p>
                </div>
                    </div>
        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block script %}


{% endblock %}