home24/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('samartsev/', admin.site.urls),
    path('', include('content.urls')),
    path('admin/', include('houses.urls')),
    path('crm-accounting/', include('crm_accounting.urls')),
    path('system-settings/', include('crm_home.urls')),
    path('users/', include('users.urls')),
]

handler404 = 'users.views.handlers404'
handler403 = 'users.views.handler403'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

houses/urls.py
from django.urls import path, include
from django.views.defaults import permission_denied, page_not_found

from . import views




app_name = 'houses'


urlpatterns = [
    path('main/', views.main_page, name='main'),

    #statistics
    path('', views.StatisticView.as_view(), name='statistics'),

    # houses
    path('houses/', views.HousesListView.as_view(), name='house_list'),
    path('houses/create/', views.HouseCreateView.as_view(), name='house_create'),
    path('houses/detail/<int:pk>/', views.HousesDetail.as_view(), name='house_detail'),
    path('houses/update/<int:pk>/', views.HouseUpdateView.as_view(), name='house_update'),
    path('houses/delete/', views.delete_house, name='delete_house'),
    path('houses/create/get-role/', views.get_role, name='get_role'),


    # flats
    path('flats/', views.FlatsListView.as_view(), name='flat_list'),
    path('flats/create/', views.FlatCreate.as_view(), name='flat_create'),
    path('flats/detail/<int:pk>/', views.FlatDetailView.as_view(), name='flat_detail'),
    path('flats/update/<int:pk>/', views.FlatUpdateView.as_view(), name='flat_update'),
    path('get-account-list/', views.get_account_list, name='get_account_list'),
    path('get-sections-and-floors/', views.get_sections_and_floors, name='get_section_and_floor'),
    path('flats/detail/<int:pk>/', views.HousesDetail.as_view(), name='flat_detail'),
    path('flats/delete/', views.delete_flat, name="delete_flat"),
    path('ajax-data-table/', views.FlatsListViewAjax.as_view(), name='get_ajax'),


    # path('create/', views.HousesListView.as_view(), name='house_create'),

    # path('about-us/', views.about, name='about'),
    # path('services/', views.services, name='services'),
    # path('contacts/', views.contacts, name='contacts'),

]

users/urls.py
from django.urls import path, include, register_converter
from . import views



app_name = 'users'
urlpatterns = [
    path('accounts/login/', views.LoginUser.as_view(), name='login'),
    path('accounts/register/', views.RegisterUserView.as_view(),
         name='register'),
    path('accounts/register-done/', views.RegisterDoneView.as_view(),
         name='register_done'),
    path('confirm/<str:sign>/', views.confirm_register,
         name='confirm_register'),
    path('accounts/admin-login/', views.LoginAdminUser.as_view(),
         name='admin-login'),
    path('accounts/logout/', views.LogoutUser.as_view(),
         name='logout'),

    path('', views.UsersListView.as_view(), name='users'),
    path('create/', views.UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', views.UserUpdateView.as_view(),
         name='user_update'),
    path('detail/<int:pk>/', views.UserDetailView.as_view(),
         name='user_detail'),
    path('delete/<int:pk>/', views.delete_user, name='user_delete'),

    path('ajax-user-list/', views.AjaxUsersListView.as_view(),
         name='ajax-users'),

    # owners
    path('owner/', views.OwnerListView.as_view(), name='owner_list'),
    path('owner/create/', views.OwnerCreateView.as_view(),
         name='owner_create'),
    path('owner/update/<int:pk>/', views.OwnerUpdateView.as_view(),
         name='owner_update'),
    path('owner/detail/<int:pk>/', views.OwnerDetailView.as_view(),
         name='owner_detail'),
    path('owner/delete/', views.OwnerListView.as_view(), name='owner_delete'),


    #CABINET

    path('cabinet/statistic/', views.CabinetStatisticView.as_view(),
         name='statistic_user_view'),
    path('cabinet/invoices/', views.CabinetInvoicesListView.as_view(),
         name='invoice_for_users'),
    path('cabinet/invoices/<int:pk>/', views.CabinetInvoicesDetail.as_view(),
         name='detail_invoice_for_users'),
    path('cabinet/invoices/ajax-request/',
         views.CabinetInvoicesAjaxList.as_view(),
         name='invoice_for_users_ajax'),

    #TARIFF
    path('cabinet/tariff/', views.CabinetTariffForFlatView.as_view(),
         name='tariff_for_users_flat'),
    #MESSAGES
    path('cabinet/messages/', views.MessageUserList.as_view(),
         name='messages_view'),
    path('cabinet/messages/ajax-list/', views.MessageUserAjaxList.as_view(),
         name='messages_user_ajax'),
    path('cabinet/messages/delete/', views.MessageUserAjaxDelete.as_view(),
         name='messages_user_delete'),
    path('cabinet/messages/<int:pk>/', views.MessageUserDetailView.as_view(),
         name='messages_user_detail'),

    #REQUESTS
    path('cabinet/master-request/',
         views.RequestUserListView.as_view(),
         name='request_user_view'),
    path('cabinet/master-request/get-ajax-list/',
         views.RequestUserAjaxListView.as_view(),
         name='request_user_ajax_list'),
    path('cabinet/master-request/create/',
         views.RequestUserCreateView.as_view(),
         name='request_user_create'),
    path('cabinet/master-request/delete/',
         views.RequestUserAjaxDelete.as_view(),
         name='request_user_delete'),

    #PROFILE
    path('cabinet/profile/',
         views.ProfileUserView.as_view(),
         name='user_profile'),
    path('cabinet/profile/update/',
         views.ProfileUserUpdate.as_view(),
         name='user_profile_update'),



    # request
    path('requests/', views.RequestListView.as_view(), name='requests_list'),
    path('requests-get-ajax/', views.RequestGetViewAjax.as_view(),
         name='requests_get_ajax_list'),
    path('delete-request-ajax/', views.RequestDeleteAjax.as_view(),
         name='requests_delete_ajax'),
    path('requests/create/', views.RequestsCreateView.as_view(),
         name='requests_create'),
    path('ajax-user-flats/', views.AjaxUserFlatsList.as_view(),
         name='ajax_user_flats'),
    path('requests/update/<int:pk>/', views.RequestUpdateView.as_view(),
         name='requests_update'),
    path('requests/detail/<int:pk>/', views.RequestDetailView.as_view(),
         name='requests_detail'),

    # MESSAGES
    path('messages/', views.MessageListView.as_view(),
         name='message_list'),
    path('messages/get-ajax-list/', views.MessageAjaxList.as_view(),
         name='message_get_ajax_list'),

    path('messages/get-ajax-house/', views.MessageAjaxHouseInfo.as_view(),
         name='message_ajax_info_for_house'),
    path('messages/delete/', views.MessageAjaxDelete.as_view(),
         name='messages_delete'),

    path('messages/get-ajax-section/', views.MessageAjaxSectionInfo.as_view(),
         name='message_ajax_info_for_section'),

    path('messages/create/', views.MessageCreateView.as_view(),
         name='message_create'),
    path('messages/detail/<int:pk>/', views.MessageDetailView.as_view(),
         name='message_detail'),
]

users/models.py
import datetime
from django.utils.translation import gettext_lazy as _

from django.db import models
from django.contrib.auth.models import AbstractUser
from home24 import settings
from django.apps import apps


class Role(models.Model):
    name = models.CharField(max_length=50)
    statistics = models.BooleanField(null=True, blank=True)
    cashbox = models.BooleanField(null=True, blank=True)
    invoice = models.BooleanField(null=True, blank=True)
    personal_account = models.BooleanField(null=True, blank=True)
    flat = models.BooleanField(null=True, blank=True)
    owner = models.BooleanField(null=True, blank=True)
    house = models.BooleanField(null=True, blank=True)
    message = models.BooleanField(null=True, blank=True)
    application = models.BooleanField(null=True, blank=True)
    meter = models.BooleanField(null=True, blank=True)
    site_management = models.BooleanField(null=True, blank=True)
    service = models.BooleanField(null=True, blank=True)
    tariff = models.BooleanField(null=True, blank=True)
    role = models.BooleanField(null=True, blank=True)
    users = models.BooleanField(null=True, blank=True)
    requisites = models.BooleanField(null=True, blank=True)

    def __str__(self):
        return self.name


def get_next_user_id():
    try:
        users = CustomUser.objects.filter(is_superuser=False).\
            order_by('-username')
        if users.exists():
            user_id = int(users.first().username) + 1
        else:
            user_id = 1
    except:
        user_id = 2
    return user_id


class CustomUser(AbstractUser):
    email = models.EmailField(_("email address"), unique=True)
    photo = models.ImageField(upload_to='users/', blank=True, null=True)
    birthday = models.DateField(null=True, blank=True)
    father_name = models.CharField(max_length=30, help_text='Отчество',
                                   null=True, blank=True, default='')
    phone = models.CharField(max_length=20, null=True, blank=True, default='')
    viber = models.CharField(max_length=20, null=True, blank=True, default='')
    telegram = models.CharField(max_length=20, null=True, blank=True,
                                default='')
    status_state = [('Активен', 'Активен'), ('Новый', 'Новый'),
                    ('Отключен', 'Отключен')]
    status = models.CharField(choices=status_state, default=status_state[1][0],
                              max_length=20, null=True, blank=True)
    username = models.IntegerField(verbose_name="User ID",
                                unique=True, help_text='Required',
                                error_messages=
                                {"unique":
                                     "Пользователь с таким ID уже существует."},
                                blank=True, null=True,
                                default=get_next_user_id)
    about = models.TextField(max_length=1000, null=True, blank=True)
    role = models.ForeignKey('Role', on_delete=models.PROTECT, null=True,
                             blank=True)

    def __str__(self):
        if self.father_name:
            return f'{self.first_name} {self.last_name} {self.father_name}'
        else:
            return f'{self.first_name} {self.last_name}'


class Message(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField(max_length=1000, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    message_address_house_id = models.ForeignKey('houses.House',
                                                 on_delete=models.SET_NULL,
                                                 null=True, blank=True)
    message_address_section_id = models.ForeignKey('houses.Section',
                                                   on_delete=models.SET_NULL,
                                                   null=True, blank=True)
    message_address_floor_id = models.ForeignKey('houses.Floor',
                                                 on_delete=models.SET_NULL,
                                                 null=True, blank=True)
    message_address_flat_id = models.ForeignKey('houses.Flat',
                                                on_delete=models.SET,
                                                null=True, blank=True)
    sender = models.ForeignKey(CustomUser, on_delete=models.SET_NULL,
                               null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Request(models.Model):
    date = models.DateField(default=datetime.datetime.now)
    time = models.TimeField(default=datetime.datetime.now)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE,
                              related_name='owner_request',
                              null=True)
    description = models.TextField(max_length=1999, blank=True, null=True)
    comment = models.TextField(max_length=1000, blank=True, null=True)
    flat = models.ForeignKey('houses.Flat', on_delete=models.PROTECT)
    masters = [("Сантехник", "Сантехник"), ("Электрик", "Электрик"),
               ("Слесарь", "Слесарь"), ("Любой специалист", "Любой специалист")]
    type_master = models.CharField(choices=masters, default=masters[0][0],
                                   max_length=50)
    status_request = [("", "Выберите..."), ("Новое", "Новое"),
                      ("В работе", "В работе"), ("Выполнено", "Выполнено")]
    status = models.CharField(choices=status_request, max_length=50,
                              default=status_request[1][0])
    master = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.PROTECT, null=True)
    created_at = models.DateTimeField(auto_now_add=True)


class MessageUsers(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    message = models.ForeignKey(Message,
                                on_delete=models.CASCADE)
    read = models.BooleanField(default=False, blank=True)

templates/users/message_form.html
{% extends 'houses/layout/base_houses.html' %}
{% load static %}
{% block title %}
    Новое сообщение
{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'content/css/content_css.css' %}" type="text/css">
{% endblock %}
{% block css_after %}
    <link rel="stylesheet" href="{% static 'users/css/message_create.css' %}">
    <script src="{% static 'content/plugins/ckeditor/ckeditor.js' %}"></script>

{% endblock %}
{% block content %}
        <input type="hidden" id="link-id" value="message-link">

    <section class="content-header" style="position: relative; display: block!important; border-bottom: 1px solid #d2d6de">
        <h1 style="color: #444; font-size: 24px"> Новое сообщение
        </h1>
        <ul class="breadcrumb" style="float:right;background: transparent!important; margin-top: 0!important;
        margin-bottom: 0!important; font-size: 12px!important; position: absolute!important;
        top: 15px!important; right: 15px!important; border-radius: 2px!important;">
            <li><a href="{% url 'houses:main' %}" style="color: #444; text-decoration: none"><i class="fa fa-home" style="margin-right: 5px"></i> Главная</a></li>
            <li class="active" style="padding: 0 0 0 10px; color: #777;"><a href="{% url 'users:message_list' %}" style="color: #444; text-decoration: none">
                <span style="color: #ccc; margin-right: 5px" >></span> Сообщения
                </a>
            </li>
            <li style="padding: 0 0 0 10px; color: #777;"><span style="color: #ccc; margin-right: 5px" >></span> Новое сообщение</li>
        </ul>
    </section>
    <form method="post" style="padding:15px">
        {% csrf_token %}
    <!-- content -->
    <section class="content content-custom" >
                <div class="box">
                    <div class="box-body">
                            <div class="row">
                            <div class="box-header with-border">
                                <h3 class="box-title"></h3>
                            </div>
                                <div class="col-xs-12">
                                     <div class="form-group">
                                        {{ form.title }}
                                         <div class="errorlist">
                                            {% if form.errors.title %}
                                                {% for field in form.errors.title %}
                                                    {{ field }}
                                                {% endfor %}
                                            {% endif %}
                                        </div>
                                        <div class="help-block">Необходимо заполнить "Заголовок"</div>
                                    </div>
                                    <div class="form-group">
                                        {{ form.text }}
                                        <script>
                                            CKEDITOR.replace( 'id_text' );
                                        </script>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <h4>Кому отправить:</h4>
                                    <div class="form-group no-margin">
                                    {{ form.message_for_deptors }}
                                    <label for="message_for_deptors">Владельцам с задолженностями</label>
                                    </div>
                                    <div class="form-group no-margin">
                                        <label for="house">ЖК</label>
                                        {{ form.message_address_house_id }}
                                    </div>
                                    <div class="form-group no-margin">
                                        <label
                                            for="id_message_address_section_id">Секция</label>
                                        <select name="message_address_section_id" id="id_message_address_section_id" class="form-select">
                                            <option value="">Всем...</option>
                                        </select>
                                    </div>
                                    <div class="form-group no-margin">
                                        <label for="id_message_address_floor_id">Этаж</label>
                                        <select name="message_address_floor_id" id="id_message_address_floor_id" class="form-select">
                                            <option value="">Всем...</option>
                                        </select>
                                    </div>
                                    <div class="form-group no-margin">
                                        <label for="id_message_address_flat_id">Квартира</label>
                                        <select name="message_address_flat_id" id="id_message_address_flat_id" class="form-select">
                                            <option value="">Всем...</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="row" style="text-align: right">
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-success" name="save">
                                            <i class="fa fa-envelope-o"></i>
                                            Отправить
                                        </button>
                                    </div>
                                    </div>
                                </div>
                    </div>
                </div>
    </section>
    </form>

    <div>

    </div>
  <script>
  </script>
{% endblock %}
{% block script %}

    <script>
        const UrlGetSectionsFloorsFlats = '{% url 'users:message_ajax_info_for_house' %}';
        const UrlGetFlatsBySection = '{% url 'users:message_ajax_info_for_section' %}';
    </script>
    <script src="{% static 'users/js/message_create.js' %}"></script>

{% endblock %}

templates/users/owner_update_form.html
{% extends 'houses/layout/base_houses.html' %}
{% load static %}
{% block title %}
    Профиль владельца
{% endblock %}
{% block css %}

    <link rel="stylesheet" href="{% static 'content/css/content_css.css' %}" type="text/css">
{% endblock %}
{% block css_after %}
    <link rel="stylesheet" href="{% static 'users/css/owner_create.css' %}">
{#<link  href="{% static 'users/dist/datepicker.css' %}" rel="stylesheet">#}
        <link rel="stylesheet" href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.10.3/themes/smoothness/jquery-ui.css">


{% endblock %}
{% block content %}
                <input type="hidden" id="link-id" value="owner-link">

    <section class="content-header" style="position: relative; display: block!important; border-bottom: 1px solid #d2d6de">
        <h1 style="color: #444; font-size: 24px">Профиль владельца
        </h1>
        <ul class="breadcrumb" style="float:right;background: transparent!important; margin-top: 0!important;
        margin-bottom: 0!important; font-size: 12px!important; position: absolute!important;
        top: 15px!important; right: 15px!important; border-radius: 2px!important;">
            <li><a href="{% url 'houses:main' %}" style="color: #444; text-decoration: none"><i class="fa fa-home" style="margin-right: 5px"></i> Главная</a></li>
            <li class="active" style="padding: 0 0 0 10px; color: #777;"><a href="{% url 'users:owner_list' %}" style="color: #444; text-decoration: none">
                <span style="color: #ccc; margin-right: 5px" >></span> Владельцы квартир
                </a>
            </li>
            <li style="padding: 0 0 0 10px; color: #777;"><span style="color: #ccc; margin-right: 5px" >></span><a href="{% url 'users:owner_detail' object.id %}" style="color: #444; text-decoration: none">  Профиль владельца</a></li>
            <li style="padding: 0 0 0 10px; color: #777;"><span style="color: #ccc; margin-right: 5px" >></span> Редактирование</li>
        </ul>
    </section>

    <!-- content -->
    <section class="content content-custom" >
        <div class="row">
            <div class="col-sm-12">
                <div class="box">
                    <div class="box-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-xs-12 col-sm-6">
                                    <div class="userAvatar">
                                        {% if object.photo %}
                                            <img src="{{ object.photo.url }}" class="img-circle pull-left img-responsive" alt="">
                                        {% else %}
                                            <img src="{% static 'content/img/empty.jpeg' %}" class="img-circle pull-left img-responsive" alt="">
                                        {% endif %}
                                        <div class="form-group" style="display: flex; flex-direction: column">
                                            {{ form.photo.label_tag }}
                                            <input type="file" name="photo" accept="image/*" id="id_photo">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-6">
                                    <div class="form-group">
                                        {{ form.status.label_tag }}
                                        {{ form.status }}
                                    </div>
                                     <div class="form-group">
                                        {{ form.username.label_tag }}
                                        {{ form.username }}
                                         {% if form.errors.username %}
                                        <div class="errorlist-password" style="color: #dd4b39">
                                            {% for field in form.errors.username %}
                                                {{ field }}
                                            {% endfor %}
                                        </div>
                                    {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12 col-sm-6">
                                    <div class="form-group">
                                        {{ form.last_name.label_tag }}
                                        {{ form.last_name }}
                                    </div>
                                    <div class="form-group">
                                        {{ form.first_name.label_tag }}
                                        {{ form.first_name }}
                                    </div>
                                    <div class="form-group">
                                        {{ form.father_name.label_tag }}
                                        {{ form.father_name }}
                                    </div>
                                    <div class="form-group" id="birtday-form">
                                        {{ form.birthday.label_tag }}
                                        <div class="input-group  ui-widget" style="position: relative">
                                            {{ form.birthday }}
{#                                                <button type="button" class="btn btn-date" id="btn-date">#}
{#                                                    <i class="fa fa-calendar"></i>#}
{#                                                </button>#}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-6">
                                    <div class="form-group">
                                        {{ form.about.label_tag }}
                                        {{ form.about }}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12 col-md-6">
                                    <h2 class="page-header">
                                        Контактные данные
                                    </h2>
                                    <div class="form-group">
                                        {{ form.phone.label_tag }}
                                        {{ form.phone }}
                                    </div>
                                    <div class="form-group">
                                        {{ form.viber.label_tag }}
                                        {{ form.viber }}
                                    </div>
                                    <div class="form-group">
                                        {{ form.telegram.label_tag }}
                                        {{ form.telegram }}
                                    </div>
                                    <div class="form-group">
                                        {{ form.email.label_tag }}
                                        {{ form.email }}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-md-6">
                                    <h2 class="page-header">
                                        Изменить пароль
                                    </h2>
                                    <div class="form-group">
                                        {{ form.password1.label_tag }}
                                        <div class="input-group">
                                            {{ form.password1 }}
                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type="button" onclick="generatePassword()">
                                                    Сгенерировать
                                                </button>
                                                <button type="button" class="btn btn-primary" id="showPass">
                                                    <i class="fa fa-eye" aria-hidden="true"></i>
                                                </button>
                                            </span>
                                            <div class="help-block">Значение «Пароль» должно содержать минимум 6 символов.</div>
                                        </div>
                                    </div>
                                {% if form.errors.password1 %}
                                            <div class="errorlist-password" style="color: #dd4b39">
                                            {% for field in form.errors.password1 %}
                                                {{ field }}
                                            {% endfor %}
                                            </div>
                                        {% endif %}
                                    <div class="form-group">
                                        {{ form.password2.label_tag }}
                                            {{ form.password2 }}
                                        <div class="help-block">Значение «Пароль» должно содержать минимум 6 символов.</div>
                                    </div>
                                    {% if form.errors.password2 %}
                                        <div class="errorlist-password" style="color: #dd4b39">
                                            {% for field in form.errors.password2 %}
                                                {{ field }}
                                            {% endfor %}
                                        </div>
                                    {% endif %}
                                </div>
                                </div>

{#                            </div>#}

{#                            <div class="form-group">#}
                                <div class="form-group" style="text-align: right">
                            <a href="{% url 'users:users' %}" class="btn btn-default" style="height: 34px; font-size: 14px; background-color: #f4f4f4; color: #444!important;
                                ">Отменить</a>
                            <button type="submit" class="btn btn-success" id="btn-save">Сохранить</button>
                                </div>
{#                            </div>#}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div>

    </div>
  <script>
  </script>
{% endblock %}
{% block script %}
{#    <script src="{% static 'users/dist/datepicker.js' %}"></script>#}

    <script>
    $(function () {
        $("#id_birthday").datepicker({
                showOn: "both",
            });
        $('.ui-datepicker-trigger').html("<i class='fa fa-calendar'></i>").addClass('btn btn-date')

    })

    </script>
    <script src="{% static 'users/js/owner_create.js' %}">
    </script>
{% endblock %}